### ISSUE TITLE
[CI] Broken GHA badge link

### ISSUE THREAD

**Issue by iamazeem** [StanfordLegion/regent-fft#3]
Hi,

The GHA badge link in the README is broken (screenshot below):

![Screenshot from 2024-07-19 14-26-03](https://github.com/user-attachments/assets/6fd5d077-0423-48be-a4f2-7de9129c5e4b)

Fixing the [workflow filename](https://github.com/StanfordLegion/regent-fft/blob/master/.github/workflows/master.yml) [here](https://github.com/StanfordLegion/regent-fft/blob/df842a3da93efc5c20898cbfe5de86712b227a38/README.md?plain=1#L4C8-L4C89) i.e. from `main.yml` to `master.yml` should fix this:

```diff
-Tests](https://github.com/StanfordLegion/regent-fft/actions/workflows/main.yml/badge.svg)](https://github.com/StanfordLegion/regent-fft/actions)
+Tests](https://github.com/StanfordLegion/regent-fft/actions/workflows/master.yml/badge.svg)](https://github.com/StanfordLegion/regent-fft/actions)
```

Preview:

![Bdage](https://github.com/StanfordLegion/regent-fft/actions/workflows/master.yml/badge.svg)

Thanks!

**Comment by elliottslaughter** [comment]
Fixed by #5.
